sudo: required
services:
  - docker

before_install:
  - docker build -t paulomedeiros88/docker-react-sample -f Dockerfile.dev .

script:
  - docker run -e CI=true paulomedeiros88/docker-react-sample npm run test
